language: cpp
dist: bionic
compiler: gcc
python: "3.6"

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages: 
    - lcov
    - gcc-9
    - g++-9

install:
- pip install -U cmake

env:
  - CC=gcc-9 CXX=g++-9

script: ./build.sh

after_success:
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

