language: cpp
dist: bionic
compiler: clang
python: "3.6"

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

before_install:
  - 'wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null'
addons:
  apt:
    sources:
    - sourceline: 'deb https://apt.kitware.com/ubuntu/ bionic main'
    packages:
    - lcov
    - cmake


script: ./build.sh

after_success:
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

