strategy:
  matrix:
    linux_python36:
      VM_IMAGE: 'ubuntu-latest'
      PYTHON_VERSION: '3.6'
    linux_python37:
      VM_IMAGE: 'ubuntu-latest'
      PYTHON_VERSION: '3.7'
    macos_python36:
      VM_IMAGE: 'macos-latest'
      PYTHON_VERSION: '3.6'
    macos_python37:
      VM_IMAGE: 'macos-latest'
      PYTHON_VERSION: '3.7'


pool:
  vmImage: '$(VM_IMAGE)'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PYTHON_VERSION)'
  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install tools'
  - script: python -m pip wheel . -w wheelhouse
    displayName: 'Build wheel'
  - task: PublishBuildArtifacts@1
    inputs: {pathtoPublish: 'wheelhouse'}

