variables:
  CIBW_BUILD: cp3?-*
  CIBW_SKIP: "*-win32 *-manylinux_i686"
  CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
  CIBW_DEPENDENCY_VERSIONS: latest

strategy:
  matrix:
    linux_python37:
      VM_IMAGE: 'ubuntu-latest'
      PYTHON_VERSION: '3.7'
    macos_python37:
      VM_IMAGE: 'macos-latest'
      PYTHON_VERSION: '3.7'


pool:
  vmImage: '$(VM_IMAGE)'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(PYTHON_VERSION)'
  - script: python -m pip install --upgrade pip setuptools wheel cibuildwheel
    displayName: 'Install tools'
  - script: python -m cibuildwheel --output-dir wheelhouse .
    displayName: 'Build wheel'
  - task: PublishBuildArtifacts@1
    inputs: {pathtoPublish: 'wheelhouse'}

