strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-latest'
    windows:
      imageName: 'windows-latest'
    Python35:
      python.version: '3.5'
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7' 

pool:
  vmImage: $(imageName)

steps:
- task: UsePythonVersion@0
- script: |
    python -m pip install --upgrade pip
    python -m pip install cibuildwheel==1.5.1
    cibuildwheel --output-dir wheelhouse .
- task: PublishBuildArtifacts@1
  inputs: {pathtoPublish: 'wheelhouse'}

