coverage:
  ignore:
    - "test_*.cc"
    - "tests/test_*.cc"
    - "tests/**/*"
    - "examples/**/*"
    - "third_party/**/*"
    - "signal_tl/**/*"

codecov:
  branch: master

comment:
  layout: "diff"
