github_url = "https://github.com/anand-bala/signal-temporal-logic/"

[version]
current = "0.1.3-post1"

# Official Semantic Versioning regex 
regex = '''
  ^(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "setup.cfg"
search = 'version = {current_version}'

[[file]]
src = "signal_tl/_version.py"
search = 'version = "{current_version}"'

[[file]]
src = "signaltl_version.cmake"
version_template = "{major}"
search = "SIGNALTL_MAJOR {current_version}"

[[file]]
src = "signaltl_version.cmake"
version_template = "{minor}"
search = "SIGNALTL_MINOR {current_version}"

[[file]]
src = "signaltl_version.cmake"
version_template = "{patch}"
search = "SIGNALTL_PATCHLEVEL {current_version}"

