name: macOS

on: [push, pull_request]

jobs:
  xcode:
    strategy:
      fail-fast: false
      matrix:
        xcode: ['11', '12']
        build_type: [Debug, Release]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-deps
      with:
        path: .deps
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/ThirdPartyDeps.cmake') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Cache build
      uses: actions/cache@v2
      env:
        cache-name: cache-build
      with:
        path: ~/.ccache/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-xcode-${{ matrix.xcode }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - name: CMake configure (Ubuntu)
      run: cmake -B build

    - working-directory: build/
      run: cmake --build . --config ${{ matrix.build_type }}

    - working-directory: build/
      run: ctest --config ${{ matrix.build_type }} --output-on-failure
